export replay_directory=/zfssa/oracle_export/replay/REPDIR
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydiy=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries1 mode=query_only replaydir=${replay_directory} &
