export replay_directory=/zfssa/oracle_export/replay/REPDIR_ARIES1_REP_041720201609
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
#wrc avdba/avdba#2ALL@ag3aries6 mode=query_only replaydir=${replay_directory} &
