export replay_directory=
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=rcmprd_wrc_client_node4.sh
