export replay_directory=
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
wrc avdba/avdba#2ALL@ag3rcmprd4 replaydir=${replay_directory} &
